<h1>Привет Андрею и Соне!</h1>
<br>
<script type="text/javascript">

<!-- This script and many more are available free online at -->
<!-- The JavaScript Source!! http://javascript.internet.com -->

<!-- Begin
function Encrypt(theText) {
output = new String;
Temp = new Array();
Temp2 = new Array();
TextSize = theText.length;
for (i = 0; i < TextSize; i++) {
	rnd = Math.round(Math.random() * 122) + 68;
	Temp[i] = theText.charCodeAt(i) + rnd;
	Temp2[i] = rnd;
}
for (i = 0; i < TextSize; i++) {
	output += String.fromCharCode(Temp[i], Temp2[i]);
}
return output;
}
function unEncrypt(theText) {
output = new String;
Temp = new Array();
Temp2 = new Array();
TextSize = theText.length;
for (i = 0; i < TextSize; i++) {
	Temp[i] = theText.charCodeAt(i);
	Temp2[i] = theText.charCodeAt(i + 1);
}
for (i = 0; i < TextSize; i = i+2) {
	output += String.fromCharCode(Temp[i] - Temp2[i]);
}
return output;
}
//  End -->
</script>

<form name=encform onsubmit="return false;">
<p>
<textarea name=box1 rows=5 cols=80>Сюда писать текст для зашифровки</textarea>
<p>
<input type=button value="Зашифровать" onClick="this.form.box2.value=Encrypt(this.form.box1.value);">
<br><p>
<textarea name=box2 rows=5 cols=80>Здесь будет зашифрованный текст//Сюда зашифрованный текст для расшифровки</textarea>
<p>
<input type=button value="расшифровать" onClick="this.form.box3.value=unEncrypt(this.form.box2.value);">
<br><p>
<textarea name=box3 rows=5 cols=80>здесь будет ваш расшифрованный текст</textarea>
</form>

